### ISSUE TITLE
Is there a method to cancel an event?

### ISSUE THREAD

**Issue by tschechniker** [saw303/grails-ic-alender#11]
Hi,

in iCal4j it is possible to cancle an Event. Is there already a method implemented?

Best regards

Tobias

**Comment by saw303** [comment]
Since version 0.4.3 it is possible to overwrite a `VEVENT`s method property. Make sure you use the same `UID` on the event as it was published.

Means if you once published an event with UID `abc8934jsdj@host`

    calendar {
        events {
            event(start: new Date(), end: new Date(), description: 'Hi all', summary: 'Short info1', uid: 'abc8934jsdj@host')
        }
    }

You need to cancel the event using the exact same UID as it was published

    calendar {
        events {
            event(start: new Date(), end: new Date(), description: 'Hi all', summary: 'Short info1', uid: 'abc8934jsdj@host', method: 'CANCEL')
        }
    }
