### ISSUE TITLE
Unable to install latest releases (0.4.3 and 0.4.2)

### ISSUE THREAD

**Issue by craigweston** [saw303/grails-ic-alender#13]
I am unable to upgrade from 0.4.0 to releases 0.4.3 or 0.4.2. The plugins cannot be found.

**Repository config:**
```
	repositories {
		grailsPlugins()
		grailsHome()
		grailsCentral()
	}
```
**Given:**
``` compile ":ic-alendar:0.4.3" ```

**Produces**:
```
		::::::::::::::::::::::::::::::::::::::::::::::
		::          UNRESOLVED DEPENDENCIES         ::
		::::::::::::::::::::::::::::::::::::::::::::::
		:: org.grails.plugins#ic-alendar;0.4.3: not found
		::::::::::::::::::::::::::::::::::::::::::::::
```
**Given:**
``` compile ":ic-alendar:0.4.2" ```

**Produces**:
```
		::::::::::::::::::::::::::::::::::::::::::::::
		::          UNRESOLVED DEPENDENCIES         ::
		::::::::::::::::::::::::::::::::::::::::::::::
		:: org.grails.plugins#ic-alendar;0.4.2: not found
		::::::::::::::::::::::::::::::::::::::::::::::
```
Setting version to 0.4.0 installs fine.

I am using grails version 2.3.5

**Comment by saw303** [comment]
Tried to reproduce it. Created a plain new Grails application and added `compile ":ic-alendar:0.4.3"` to the `BuildConfig.groovy`. Run `grails war` and all dependencies have been resolved succesfully. Maybe a temporary problem with the Grails Plugin Repository?

**Comment by craigweston** [comment]
Must be, thanks for looking into it.

**Comment by craigweston** [comment]
Just tried it again and 0.4.3 was installed fine, so I guess it was just a temporary issue. Thanks again.
