### ISSUE TITLE
Add Update/Cancel event support

### ISSUE THREAD

**Issue by demon101** [saw303/grails-ic-alender#19]
For update and delete of event STATUS, METHOD, SEQUENCE field is required
http://stackoverflow.com/questions/45453/icalendar-and-event-updates-not-working-in-outlook

METHOD filed supported only in event, not calendar.

**Comment by demon101** [comment]
any estimations?

**Comment by saw303** [comment]
Probably done by upcoming  Monday or Tuesday. Grails 3.x or back port to Grails 2?

**Comment by demon101** [comment]
@saw303  really good news. We are using grails 3.1

**Comment by saw303** [comment]
Will this change work for your purpose?

```
calendar(method: 'REQUEST') {
     events {
          event start: new Date(), end: new Date(), description: 'A', summary: 'B', sequence: 12, status: 'CANCELLED', uid: '666', method: 'CANCEL'
     }
}
```

This will produce the following output 

```
BEGIN:VCALENDAR
PRODID:-//Grails iCalendar plugin//NONSGML Grails iCalendar plugin//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
DTSTAMP:20170223T194523Z
DTSTART;TZID=Europe/Zurich:20170223T204500
DTEND;TZID=Europe/Zurich:20170223T204500
SUMMARY:B
UID:666
STATUS:CANCELLED
SEQUENCE:12
TZID:Europe/Zurich
DESCRIPTION:A
ORGANIZER:
METHOD:CANCEL
END:VEVENT
END:VCALENDAR
```

**Comment by demon101** [comment]
@saw303 I think yes.

**Comment by saw303** [comment]
Released https://bintray.com/saw303/plugins/org.grails.plugins%3AiCalendar/0.6.1
