### ISSUE TITLE
Dependencies of ical4j:2.0.0 kill application with Spring security 

### ISSUE THREAD

**Issue by demon101** [saw303/grails-ic-alender#21]
New version (0.6.1) dependancies
> +--- org.grails.plugins:iCalendar:0.6.1
> |    \--- org.mnode.ical4j:ical4j:2.0.0
> |         +--- org.slf4j:slf4j-api:1.7.10 -> 1.7.21
> |         +--- org.apache.commons:commons-collections4:4.0
> |         +--- org.codehaus.groovy:groovy-all:2.3.2 -> 2.4.7
> |         +--- biz.aQute.bnd:bndlib:2.3.0
> |         |    \--- org.osgi:org.osgi.core:4.3.1
> |         +--- org.apache.commons:commons-lang3:3.3.2
> |         \--- commons-codec:commons-codec:1.9

10Mb of new dependencies =)

Previous (0.6.0) 
>  org.grails.plugins:iCalendar:0.6.0
> |    \--- org.mnode.ical4j:ical4j:1.0.7
> |         +--- commons-logging:commons-logging:1.1.3 -> 1.2
> |         +--- commons-codec:commons-codec:1.8 -> 1.9
> |         +--- commons-lang:commons-lang:2.6
> |         \--- backport-util-concurrent:backport-util-concurrent:3.1

Grails 3.1.15
The problem reproducible only on tomcat 

Now I'm trying to exclude dependencies, without success. 

> compile ('org.grails.plugins:iCalendar:0.6.1'){
>         exclude group:'org.slf4j'
>         exclude group:'biz.aQute.bnd'
>         exclude group:'org.codehaus.groovy'
>         exclude group:'commons-codec'
>     }

Is it possible rollback dependencies ?

**Comment by demon101** [comment]
> java.lang.NullPointerException: null
> at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.findActionRoles(AnnotationFilterInvocationDefinition.groovy:458)
> at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.findAnnotations(AnnotationFilterInvocationDefinition.groovy:425)
> at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.findAnnotations(AnnotationFilterInvocationDefinition.groovy)
> at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.findControllerAnnotations(AnnotationFilterInvocationDefinition.groovy:382)
> at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.initialize(AnnotationFilterInvocationDefinition.groovy:223)
> at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition$initialize.call(Unknown Source)

**Comment by saw303** [comment]
Use https://bintray.com/saw303/plugins/org.grails.plugins%3AiCalendar/0.6.2

**Comment by demon101** [comment]
@saw303 
Funny, same results. Application context corrupted =)
Will check on Monday

**Comment by demon101** [comment]
org.mnode.ical4j:ical4j:1.0.7
|         +--- commons-logging:commons-logging:1.1.3 -> 1.2
|         +--- commons-codec:commons-codec:1.8 -> 1.9
|         +--- commons-lang:commons-lang:2.6
|         \--- backport-util-concurrent:backport-util-concurrent:3.1

**Comment by demon101** [comment]
In new versions (0.6.1 & 0.6.2) jars /grails/plugins/ic/alendar/ApplicationLoader.class presented. 
It looks like a reason for failing of spring context

content:

> package grails.plugins.ic.alendar;
> 
> import grails.plugins.ic.alendar.Application;
> import org.codehaus.groovy.runtime.ScriptBytecodeAdapter;
> import org.codehaus.groovy.runtime.callsite.CallSite;
> import org.grails.boot.context.web.GrailsAppServletInitializer;
> import org.springframework.boot.builder.SpringApplicationBuilder;
> import org.springframework.web.WebApplicationInitializer;
> 
> public class ApplicationLoader extends GrailsAppServletInitializer implements WebApplicationInitializer {
>     public ApplicationLoader() {
>         CallSite[] var1 = $getCallSiteArray();
>     }
> 
>     protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
>         CallSite[] var2 = $getCallSiteArray();
>         return (SpringApplicationBuilder)ScriptBytecodeAdapter.castToType(var2[0].call(application, Application.class), SpringApplicationBuilder.class);
>     }
> }

**Comment by saw303** [comment]
use `gradlew publishToMavenLocal`

**Comment by demon101** [comment]
Have you changed gradle version?

I can't find ApplicationLoader class at any plugins.
Looks like a reason for app fail

**Comment by demon101** [comment]
Hi @saw303, have a look at comment https://github.com/grails/grails-core/issues/10569#issuecomment-315376018

Problem with the new version of your plugin caused by ApplicationLoader class. I don't know, why it presented in the plugin, but it produces problems.

**Comment by Guito** [comment]
Is there any reason this was closed? I'm having the same issue and I have had to go back to 0.6.0

**Comment by saw303** [comment]
It has been closed since plugin version 0.6.2 does not use iCal4J version 2.x. See https://bintray.com/saw303/plugins/download_file?file_path=org%2Fgrails%2Fplugins%2FiCalendar%2F0.6.2%2FiCalendar-0.6.2.pom

**Comment by Guito** [comment]
So, is there any solution?

**Comment by saw303** [comment]
Currently no. Any contributions are welcome

**Comment by Guito** [comment]
Ok, to be honest I have no idea on how to fix it and it would take me a lot of time to understand everything, so for the moment I'll keep 0.6.0. If I need to update I will try to fix it.

**Comment by demon101** [comment]
The app stops failing after removing application.groovy from plugin
The bug was fixed in the issue:
https://github.com/grails/grails-core/issues/10569#issuecomment-315376018

But the version 3.2.12 not released

**Comment by saw303** [comment]
Please try version 0.6.3

**Comment by demon101** [comment]
works for me! Thx!

**Comment by saw303** [comment]
@demon101 I'm glad it works. Thank you for your input and patience. 

@Guito you might wanna give 0.6.3 a try?

**Comment by Guito** [comment]
@saw303 I confirm it works! Thank you very much for your effort.
