### ISSUE TITLE
Is there a way to set the custom uid for an event ?

### ISSUE THREAD

**Issue by imranmir** [saw303/grails-ic-alender#9]
I cant find a way to do this, as I also want to update the events. On `ICalendarBuilder.groovy:156`, I see:

    currentEvent.properties << new UidGenerator(null, 'iCalPlugin-Grails').generateUid()

This makes me think that it may be just hard coded. Am I right ? The idea is to update an event by setting the same uid in an event.

**Comment by saw303** [comment]
You can provide it by using the property `uid` on an event.

    calendar {
        events {
            event(start: new Date(), end: new Date(), description: 'Hi all', summary: 'Short info1', uid: '<your custom uid>')
        }
    }

**Comment by imranmir** [comment]
Great :)
